In [1]:
from connector import odps
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [25]:
tablename = 'Qkids_V2.prt_student_consume_cohort'
table = odps.get_table(tablename)
temp_list = list()
for p in  table.partitions:
    for row in odps.read_table(tablename, partition = p.name):
        record = [*row.values, p.name[4:10]] 
        temp_list.append(record)
df = pd.DataFrame(temp_list, columns = ['registe', 'num', 'ds', 'month'])

ds='201701'
ds='201702'
ds='201703'
ds='201704'
ds='201705'
ds='201706'
ds='201707'
ds='201708'
ds='201709'
ds='201710'
ds='201711'
ds='201712'
ds='201801'
ds='201802'
ds='201803'
ds='201804'
ds='201805'
ds='201806'
ds='201807'
ds='201808'
ds='201809'
ds='201810'
ds='201811'
ds='201812'
ds='201901'
ds='201902'
ds='201903'
ds='201904'
ds='201905'

In [26]:
cohort = df.pivot_table(values= 'num', index='registe', columns= 'month')
cohort

month,201706,201707,201708,201709,201710,201711,201712,201801,201802,201803,...,201808,201809,201810,201811,201812,201901,201902,201903,201904,201905
registe,,,,,,,,,,,,,,,,,,,,,
201511,29.0,11.0,2.0,1.0,NaN,NaN,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,8.0,2.0,15.0,NaN,NaN,7.0
201512,56.0,436.0,346.0,39.0,98.0,218.0,223.0,249.0,172.0,202.0,...,367.0,126.0,142.0,86.0,141.0,139.0,123.0,162.0,96.0,58.0
201601,NaN,8.0,14.0,31.0,47.0,122.0,190.0,212.0,194.0,214.0,...,424.0,217.0,225.0,277.0,294.0,293.0,194.0,352.0,300.0,178.0
201602,3.0,4.0,NaN,15.0,23.0,92.0,152.0,176.0,188.0,183.0,...,602.0,313.0,334.0,336.0,317.0,295.0,284.0,379.0,348.0,232.0
201603,1.0,NaN,NaN,21.0,90.0,407.0,550.0,670.0,596.0,728.0,...,1449.0,687.0,445.0,571.0,633.0,874.0,758.0,858.0,599.0,360.0
201604,18.0,12.0,8.0,42.0,129.0,821.0,1511.0,1792.0,1629.0,1728.0,...,4035.0,1618.0,1550.0,1745.0,1955.0,2314.0,1919.0,2282.0,1945.0,1274.0
201605,2.0,7.0,17.0,20.0,115.0,801.0,1383.0,1448.0,1506.0,1384.0,...,3699.0,1442.0,1339.0,1471.0,1475.0,1939.0,1536.0,1708.0,1494.0,982.0
201606,NaN,NaN,NaN,13.0,158.0,1203.0,1928.0,2260.0,2143.0,2622.0,...,5560.0,2322.0,2098.0,2049.0,2180.0,2611.0,2301.0,2750.0,2033.0,1347.0
201607,NaN,NaN,NaN,10.0,321.0,2265.0,4444.0,4920.0,4760.0,4463.0,...,11819.0,4564.0,3969.0,4130.0,5231.0,6346.0,5037.0,5271.0,4069.0,2811.0
201608,NaN,NaN,NaN,45.0,293.0,2227.0,4039.0,4619.0,4452.0,4092.0,...,10285.0,3559.0,3629.0,3708.0,4190.0,5386.0,4383.0,4689.0,3645.0,2382.0
201609,NaN,NaN,4.0,18.0,318.0,2176.0,3870.0,3951.0,3928.0,3734.0,...,9454.0,3328.0,2873.0,3129.0,3639.0,4798.0,3969.0,4320.0,3196.0,2161.0
201610,NaN,NaN,NaN,22.0,311.0,2644.0,4379.0,4933.0,4948.0,4475.0,...,10995.0,4287.0,3999.0,4489.0,5215.0,6412.0,5366.0,5620.0,4281.0,2733.0
201611,NaN,NaN,NaN,20.0,396.0,3952.0,7080.0,7513.0,8099.0,6414.0,...,17554.0,5962.0,5573.0,6159.0,7869.0,9540.0,8134.0,7979.0,5712.0,3801.0
201612,NaN,NaN,NaN,34.0,655.0,5082.0,9128.0,9890.0,10024.0,8376.0,...,21304.0,7243.0,6457.0,7221.0,8430.0,11446.0,9258.0,9140.0,6943.0,4729.0
201701,NaN,NaN,9.0,49.0,319.0,2558.0,4546.0,4758.0,5128.0,4380.0,...,11109.0,3844.0,3540.0,3635.0,4522.0,5987.0,4618.0,4855.0,3390.0,2184.0
201702,NaN,NaN,NaN,7.0,408.0,3174.0,5304.0,5244.0,5248.0,5442.0,...,11752.0,4359.0,3793.0,3981.0,4692.0,6034.0,5024.0,5320.0,3811.0,2644.0
201703,NaN,NaN,19.0,102.0,873.0,6592.0,11423.0,11623.0,11866.0,10291.0,...,25928.0,9106.0,8473.0,8860.0,10793.0,14128.0,11381.0,11970.0,8818.0,5855.0
201704,NaN,NaN,1.0,2.0,622.0,4422.0,7303.0,7512.0,7028.0,6662.0,...,15328.0,5382.0,4908.0,5474.0,6605.0,8416.0,6518.0,6530.0,5097.0,3210.0
201705,NaN,NaN,42.0,141.0,1836.0,15756.0,29203.0,30820.0,31494.0,24088.0,...,69094.0,21898.0,19855.0,20955.0,26972.0,35612.0,27961.0,28804.0,20302.0,13620.0
201706,NaN,NaN,15.0,102.0,1941.0,16474.0,30064.0,32343.0,33586.0,25344.0,...,74393.0,23687.0,21237.0,22798.0,28707.0,37294.0,29748.0,30200.0,21668.0,14338.0
201707,NaN,NaN,52.0,150.0,2325.0,16003.0,29193.0,29678.0,32382.0,23833.0,...,66655.0,21059.0,18981.0,20390.0,25158.0,31796.0,26874.0,26399.0,18826.0,12347.0
201708,NaN,NaN,103.0,369.0,2085.0,12474.0,20252.0,21115.0,20638.0,18912.0,...,44259.0,16154.0,14071.0,14681.0,17798.0,22266.0,18107.0,20534.0,14737.0,9548.0
201709,NaN,NaN,NaN,239.0,1521.0,6931.0,9639.0,8884.0,7117.0,8412.0,...,15598.0,8095.0,7171.0,7240.0,8267.0,9220.0,6992.0,9453.0,7176.0,4411.0
201710,NaN,NaN,NaN,NaN,1111.0,6075.0,7174.0,6104.0,4958.0,5190.0,...,9240.0,4632.0,4562.0,4547.0,5157.0,5909.0,4444.0,6007.0,4480.0,2991.0
201711,NaN,NaN,NaN,NaN,NaN,19807.0,48994.0,24538.0,25705.0,15211.0,...,38541.0,15335.0,14788.0,16834.0,19811.0,22276.0,18403.0,19234.0,14157.0,8714.0
201712,NaN,NaN,NaN,NaN,NaN,3.0,13751.0,46768.0,71567.0,26399.0,...,71406.0,26541.0,25402.0,29554.0,34613.0,42664.0,34698.0,34582.0,25465.0,16716.0
201801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39407.0,94365.0,29501.0,...,67108.0,24682.0,22786.0,26091.0,30678.0,37867.0,32737.0,30527.0,22262.0,14621.0
201802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27370.0,16999.0,...,24703.0,9752.0,8976.0,10349.0,11976.0,13857.0,12191.0,12005.0,8722.0,5730.0
201803,NaN,NaN,NaN,NaN,NaN,15.0,12.0,8.0,10.0,18802.0,...,33890.0,16944.0,15529.0,16782.0,18709.0,21271.0,16397.0,21106.0,15578.0,9859.0
201804,NaN,NaN,NaN,NaN,NaN,23.0,11.0,21.0,8.0,7.0,...,26471.0,11696.0,10670.0,12166.0,13860.0,15071.0,11908.0,15144.0,11743.0,7643.0
201805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,111297.0,35112.0,30623.0,37517.0,41046.0,47951.0,39908.0,40331.0,30084.0,20424.0
201806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,177139.0,51087.0,43665.0,53707.0,59046.0,66908.0,55593.0,55255.0,40825.0,26642.0
201807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,310291.0,74178.0,57188.0,67350.0,70929.0,79402.0,68309.0,69429.0,50364.0,33530.0
201808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,150106.0,67955.0,42279.0,48848.0,50191.0,53003.0,44355.0,47367.0,34497.0,22134.0
201809,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30828.0,44055.0,46617.0,46378.0,42942.0,34355.0,37958.0,28067.0,18229.0
201810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,18590.0,34915.0,25628.0,22527.0,15692.0,19984.0,15011.0,10157.0
201811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,60107.0,114414.0,76708.0,38005.0,41382.0,29580.0,18819.0
201812,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,61064.0,112367.0,91956.0,57463.0,34591.0,21830.0
201901,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,62882.0,123202.0,65689.0,36756.0,22615.0
201902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,25038.0,37310.0,19959.0,12137.0
201903,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36680.0,40904.0,20131.0
201904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29330.0,24954.0
201905,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16395.0